# Generated by Django 2.1 on 2019-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imaal_t',
            fields=[
                ('imaal001', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='品号')),
                ('imaal003', models.CharField(max_length=100, verbose_name='名称')),
                ('imaal004', models.CharField(max_length=100, verbose_name='规格')),
                ('imaalent', models.CharField(max_length=20, verbose_name='企业代码')),
            ],
            options={
                'verbose_name': '品号名称',
                'verbose_name_plural': '品号名称',
                'db_table': 'imaal_t',
                'ordering': ['imaal001'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ooag_t',
            fields=[
                ('ooag011', models.CharField(max_length=10, verbose_name='姓名')),
                ('ooagent', models.CharField(max_length=10, verbose_name='企业编号')),
                ('ooag001', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='员工编号')),
                ('ooag003', models.CharField(max_length=10, verbose_name='归属部门')),
                ('ooag004', models.CharField(max_length=10, verbose_name='歸屬營運據點')),
                ('ooag005', models.CharField(max_length=10, verbose_name='職稱')),
                ('ooag006', models.CharField(max_length=50, verbose_name='銀行行號/郵局局號')),
                ('ooag007', models.CharField(max_length=50, verbose_name='帳號')),
                ('ooag015', models.CharField(max_length=10, verbose_name='员工核决层级')),
                ('ooag016', models.BooleanField(verbose_name='启用代理人')),
                ('ooag017', models.CharField(max_length=10, verbose_name='代理人员工编号')),
                ('ooagstus', models.CharField(max_length=10, verbose_name='状态码')),
                ('ooagmoddt', models.DateField(verbose_name='最近修改如')),
            ],
            options={
                'verbose_name': '员工编号',
                'verbose_name_plural': '员工编号',
                'db_table': 'ooag_t',
                'ordering': ['ooag001'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='oofc_t',
            fields=[
                ('oofc008', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='通訊類型')),
                ('oofc003', models.CharField(max_length=100, verbose_name='聯絡對象')),
                ('oofc012', models.CharField(max_length=100, verbose_name='邮箱')),
                ('oofc011', models.CharField(max_length=20, verbose_name='簡要說明')),
                ('oofcstus', models.CharField(max_length=100, verbose_name='狀態碼')),
                ('oofccrtdt', models.CharField(max_length=100, verbose_name='创建日')),
            ],
            options={
                'verbose_name': '通訊方式',
                'verbose_name_plural': '通訊方式',
                'db_table': 'oofc_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pmaal_t',
            fields=[
                ('pmaal004', models.CharField(editable=False, max_length=20, verbose_name='供应商简称')),
                ('pmaal003', models.CharField(editable=False, max_length=20, verbose_name='供应商全称')),
                ('pmaal002', models.CharField(editable=False, max_length=10, verbose_name='语言')),
                ('pmaal001', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='供应商编码')),
                ('pmaalent', models.CharField(editable=False, max_length=10, verbose_name='企业编号')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'pmaal_t',
                'ordering': ['pmaal001'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pmdl_t',
            fields=[
                ('pmdldocdt', models.DateField(verbose_name='采购日期')),
                ('pmdldocno', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='采购单号')),
                ('pmdl025', models.CharField(max_length=100, verbose_name='送货地址')),
                ('pmdl015', models.CharField(max_length=10, verbose_name='币种')),
                ('pmdl005', models.CharField(choices=[('1', '采购'), ('2', '加工')], max_length=10, verbose_name='分类')),
                ('pmdl044', models.TextField(verbose_name='备注')),
                ('pmdlstus', models.CharField(choices=[('A', '已核准'), ('C', '结案'), ('D', '抽单'), ('F', '已发出'), ('M', '成本结案'), ('N', '未审核'), ('R', '拒绝'), ('W', '送签中'), ('X', '作废'), ('N', '未审核'), ('Y', '已审核'), ('E', '终止')], max_length=10, verbose_name='状态')),
                ('pmdlsite', models.CharField(max_length=10, verbose_name='公司别')),
            ],
            options={
                'verbose_name': '采购单主表',
                'verbose_name_plural': '采购单主表',
                'db_table': 'pmdl_t',
                'ordering': ['-pmdldocdt'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pmdn_t',
            fields=[
                ('pmdnseq', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='序号')),
                ('pmdn005', models.CharField(max_length=10, verbose_name='类别')),
                ('pmdn006', models.CharField(max_length=10, verbose_name='单位')),
                ('pmdn007', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='数量')),
                ('pmdn015', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='单价')),
                ('pmdn012', models.DateField(verbose_name='出货日期')),
                ('pmdn013', models.DateField(verbose_name='到厂日期')),
                ('pmdn014', models.DateField(verbose_name='到庫日期')),
                ('pmdnua004', models.DateField(verbose_name='供方回复交期')),
                ('pmdnua005', models.TextField(verbose_name='供方说明')),
                ('pmdnua006', models.DateTimeField(verbose_name='供方回复时间')),
                ('pmdnua007', models.CharField(max_length=20, verbose_name='回复人')),
                ('pmdnua026', models.CharField(max_length=20, verbose_name='PO')),
                ('pmdn025', models.CharField(max_length=120, verbose_name='收获地址')),
                ('pmdn045', models.CharField(max_length=20, verbose_name='行状态')),
                ('pmdn020', models.CharField(max_length=20, verbose_name='紧急度')),
            ],
            options={
                'verbose_name': '采购单子表',
                'verbose_name_plural': '采购单子表',
                'db_table': 'pmdn_t',
                'ordering': ['-pmdn012'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pmdo_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmdo019', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='已入庫量')),
                ('pmdo021', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='交货状态')),
                ('pmdo015', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='已收貨量')),
                ('pmdo016', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='驗退量')),
            ],
            options={
                'verbose_name': '采购交期明细档',
                'verbose_name_plural': '采购交期明细档',
                'db_table': 'pmdo_t',
                'ordering': ['pmdo019'],
                'managed': False,
            },
        ),
    ]
