# Generated by Django 2.1 on 2019-06-13 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='code_apba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20, null=True, verbose_name='编码')),
                ('gsb', models.CharField(max_length=20, null=True, verbose_name='公司')),
                ('paybill', models.CharField(max_length=30, null=True, verbose_name='对账单号')),
                ('lwmc', models.CharField(max_length=520, null=True, verbose_name='货物劳务名称')),
                ('ggxh', models.CharField(max_length=520, null=True, verbose_name='规格     .')),
                ('dw', models.CharField(max_length=6, null=True, verbose_name='计量单位')),
                ('sl', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='数量')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='金额')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='税额')),
                ('totalcash', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='合计')),
            ],
            options={
                'verbose_name': '对账单品号汇总',
                'verbose_name_plural': '对账单品号汇总',
                'db_table': 'code_apba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='code_pmdnt200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, null=True, verbose_name='公司')),
                ('jc', models.CharField(max_length=20, null=True, verbose_name='供应商')),
                ('sno', models.CharField(max_length=20, null=True, verbose_name='编号')),
                ('code', models.CharField(max_length=20, null=True, verbose_name='品号')),
                ('name', models.CharField(max_length=520, null=True, verbose_name='品名     .')),
                ('spec', models.CharField(max_length=520, null=True, verbose_name='规格     .')),
                ('unit', models.CharField(max_length=6, null=True, verbose_name='计量单位')),
                ('quan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='采购量')),
                ('okquan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='已交数量')),
                ('noquan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='未交量')),
            ],
            options={
                'verbose_name': '未完成采购单品号汇总',
                'verbose_name_plural': '未完成采购单品号汇总',
                'db_table': 'code_pmdnt200',
                'ordering': ['-code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='week_pmdnt200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20, null=True, verbose_name='编号')),
                ('jc', models.CharField(max_length=20, null=True, verbose_name='供应商')),
                ('zc', models.CharField(max_length=7, null=True, verbose_name='周次')),
                ('company', models.CharField(max_length=20, null=True, verbose_name='公司')),
                ('code', models.CharField(max_length=20, null=True, verbose_name='品号')),
                ('name', models.CharField(max_length=520, null=True, verbose_name='品名     .')),
                ('spec', models.CharField(max_length=520, null=True, verbose_name='规格     .')),
                ('unit', models.CharField(max_length=6, null=True, verbose_name='计量单位')),
                ('quan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='采购量')),
                ('okquan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='已交数量')),
                ('noquan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='未交量')),
            ],
            options={
                'verbose_name': '未完成采购单周次汇总',
                'verbose_name_plural': '未完成采购单周次汇总',
                'db_table': 'week_pmdnt200',
                'ordering': ['zc', 'code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pmdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('keywords', models.CharField(blank=True, max_length=120, null=True, verbose_name='关键词')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('tp', models.CharField(choices=[('00', '系统手册'), ('10', '业务文档')], default='10', max_length=2, verbose_name='类别')),
                ('business_domain', models.CharField(default='OT', max_length=4, verbose_name='业务域')),
                ('status', models.CharField(choices=[('0', '草稿'), ('1', '已发布')], default='0', max_length=2, verbose_name='状态')),
                ('pmdgsite', models.CharField(max_length=20, verbose_name='公司别')),
                ('pmdgdocno', models.CharField(max_length=30, verbose_name='询价单号')),
                ('pmdgseq', models.CharField(max_length=10, verbose_name='项次')),
                ('pmdg001', models.CharField(choices=[('Y', '外加工'), ('N', '采购')], max_length=1, verbose_name='属性')),
                ('pmdg002', models.CharField(max_length=20, verbose_name='供应商编号')),
                ('pmaal004', models.CharField(max_length=60, verbose_name='供应商简称')),
                ('pmdg003', models.CharField(max_length=20, verbose_name='品号')),
                ('imaal003', models.CharField(max_length=520, verbose_name='品名')),
                ('imaal004', models.CharField(max_length=520, verbose_name='规格')),
                ('pmdgua006', models.CharField(choices=[('0', '草稿'), ('1', '已发布')], max_length=1, verbose_name='报价分类')),
                ('pmdg007', models.IntegerField(verbose_name='询价数量')),
                ('pmdg008', models.CharField(max_length=20, verbose_name='询价单位')),
                ('pmdg009', models.BooleanField(default=0, verbose_name='分量计价否')),
                ('pmdg011', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='税率')),
                ('pmdgud014', models.IntegerField(verbose_name='最小包装量')),
                ('pmdg013', models.IntegerField(verbose_name='最低采购量')),
                ('pmdgua007', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='产品报价含税')),
                ('pmdgud013', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='理论重量首次报价[按g]')),
                ('pmdgud012', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='模具费报价含税')),
                ('pmdg017', models.DateField(auto_now_add=True, verbose_name='有效日期')),
                ('pmdg030', models.TextField(blank=True, null=True, verbose_name='询价单位')),
                ('pmdf002', models.CharField(max_length=20, verbose_name='工号')),
                ('ooag011', models.CharField(max_length=60, verbose_name='姓名')),
                ('checkid', models.BooleanField(verbose_name='提交')),
                ('checkman', models.CharField(max_length=60, verbose_name='提交人')),
                ('chktime', models.DateTimeField(auto_now=True, null=True, verbose_name='提交时间')),
               # ('approveman', models.CharField(max_length=60, verbose_name='采购员')),
                ('approvetime', models.DateTimeField(auto_now=True, null=True, verbose_name='确认时间')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '询价',
                'verbose_name_plural': '询价',
            },
        ),
        migrations.CreateModel(
            name='pmdgfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='大小')),
                ('attach', models.FileField(blank=True, null=True, upload_to='doc', verbose_name='附件')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('pmdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.pmdg')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('basedata.apca_t',),
        ),
        migrations.AlterModelOptions(
            name='apba_t',
            options={'managed': False, 'ordering': ['paybill'], 'verbose_name': '财务对账单', 'verbose_name_plural': '财务对账单'},
        ),
        migrations.AlterModelOptions(
            name='apca_t',
            options={'managed': False, 'ordering': ['paydate'], 'verbose_name': '付款计划', 'verbose_name_plural': '付款计划'},
        ),
    ]
