# Generated by Django 3.0.3 on 2020-03-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_auto_20190613_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleSummary',
        ),
        migrations.CreateModel(
            name='ApbacodeSummary',
            fields=[
            ],
            options={
                'verbose_name': '对账单按品号汇总',
                'verbose_name_plural': '对账单按品号汇总',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('basedata.apba_t',),
        ),
        migrations.AlterModelOptions(
            name='pmdg',
            options={'verbose_name': '供应商报价', 'verbose_name_plural': '供应商报价'},
        ),
        migrations.AlterModelOptions(
            name='pmdgfile',
            options={'managed': False, 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='approveman',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='approvetime',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='checkid',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='checkman',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='chktime',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='end',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='modification',
        ),
        migrations.RemoveField(
            model_name='pmdg',
            name='modifier',
        ),
        migrations.AddField(
            model_name='pmdg',
            name='attach1',
            field=models.FileField(blank=True, help_text='此处附件需要在提交审批前加入', null=True, upload_to='doc', verbose_name='附件1'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='attach2',
            field=models.FileField(blank=True, null=True, upload_to='doc', verbose_name='附件2'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='attach3',
            field=models.FileField(blank=True, null=True, upload_to='doc', verbose_name='附件3'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdguaqt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='其他费用[如喷漆嵌件移印]'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud005',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='材质及表面要求'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud011',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='与供应商交涉后，最终价格，采购员在终审时填写', max_digits=14, null=True, verbose_name='产品采购员议价'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud015',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='与供应商交涉后，最终价格，采购员在终审时填写', max_digits=14, null=True, verbose_name='模具费采购员议价'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud017',
            field=models.IntegerField(default=0, null=True, verbose_name='交期(天)'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud018',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='毛重(g)'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud019',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='净重(g)'),
        ),
        migrations.AddField(
            model_name='pmdg',
            name='pmdgud020',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='理论重量(g)'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='creator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='ooag011',
            field=models.CharField(max_length=60, verbose_name='采购人员'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='pmdg001',
            field=models.CharField(max_length=10, verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='pmdg009',
            field=models.BooleanField(default=0, verbose_name='是否分量计价'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='pmdg030',
            field=models.TextField(blank=True, null=True, verbose_name='报价公式及其他说明'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='pmdgua006',
            field=models.IntegerField(choices=[(1, '最终报价'), (2, '理论重量首次报价')], help_text='选择【最终报价】时填写【产品报价含税】，选择【理论重量首次报价】时填写【理论重量首次报价[按g]】', verbose_name='报价分类'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='status',
            field=models.CharField(choices=[('0', '未提交'), ('1', '已提交'), ('2', '处理中'), ('3', '已完成')], default='0', max_length=2, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='pmdg',
            name='tp',
            field=models.CharField(choices=[('0', '未提交'), ('1', '已提交'), ('2', '处理中'), ('3', '已完成')], default='10', max_length=2, verbose_name='类别'),
        ),
    ]
