# Generated by Django 2.1 on 2019-07-07 20:08

import builtins
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(blank=True, max_length=3, null=True, verbose_name='公司别')),
                ('jc', models.CharField(max_length=40, null=True, verbose_name='简称')),
                ('bbill', models.CharField(max_length=40, null=True, verbose_name='采购单号')),
                ('bclass', models.CharField(max_length=20, null=True, verbose_name='采购单别')),
                ('bnum', models.IntegerField(null=True, verbose_name='序号')),
                ('buydate', models.DateField(null=True, verbose_name='采购日期')),
                ('code', models.CharField(max_length=20, null=True, verbose_name='品号')),
                ('name', models.CharField(max_length=520, null=True, verbose_name='品名')),
                ('spec', models.CharField(max_length=520, null=True, verbose_name='规格')),
                ('unit', models.CharField(max_length=6, null=True, verbose_name='计量单位')),
                ('quan', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='采购量')),
                ('okquan', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='已交数量')),
                ('noquan', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='未交量')),
                ('sendquan', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='发货数量')),
                ('arrive_date', models.DateTimeField(verbose_name='检验完成时间')),
                ('jokquan', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='验收数量')),
                ('jcnoquan', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='验退数量')),
                ('sdate', models.DateField(null=True, verbose_name='供方回复到货日')),
                ('sbill', models.CharField(max_length=40, null=True, verbose_name='来源单号')),
                ('description', models.CharField(max_length=140, null=True, verbose_name='备注描述')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Pmdnt200', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '发货单细节',
                'verbose_name_plural': '发货单细节',
            },
        ),
        migrations.CreateModel(
            name='deliverynote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建者')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='修改者')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('usercode', models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商代码')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商简称')),
                ('order_date', models.DateTimeField(verbose_name='送货时间')),
                ('arrive_date', models.DateTimeField(verbose_name='确认送达时间')),
                ('buycode', models.CharField(blank=True, max_length=20, null=True, verbose_name='采购员代码')),
                ('buyname', models.CharField(blank=True, max_length=20, null=True, verbose_name='采购员')),
                ('unitcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='收货单位代码')),
                ('unitaddr', models.CharField(blank=True, max_length=200, null=True, verbose_name='收货地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='送货单描述')),
                ('status', models.CharField(choices=[('0', '制单'), ('1', '发货'), ('4', '作废'), ('9', '收货'), ('12', '检验')], default='0', max_length=2, verbose_name='状态')),
            ],
            options={
                'verbose_name': '送货单',
                'verbose_name_plural': '送货单',
            },
            managers=[
                ('mine', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='factoryaddr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=builtins.id)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=20, verbose_name='名称代码')),
                ('address', models.CharField(max_length=220, verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '供应商送货地址',
                'verbose_name_plural': '供应商送货地址',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.factoryaddr', verbose_name='收货单位'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.deliverynote', verbose_name='发货单主表'),
        ),
    ]
