# Generated by Django 2.1 on 2019-07-17 11:16

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterpmdn200',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=builtins.id)),
                ('allname', models.CharField(max_length=140, null=True, verbose_name='全称')),
                ('bbill', models.CharField(max_length=40, null=True, verbose_name='采购单号')),
                ('bclass', models.CharField(max_length=20, null=True, verbose_name='采购单别')),
                ('bnum', models.IntegerField(null=True, verbose_name='序号')),
                ('buydate', models.DateField(null=True, verbose_name='采购日期')),
                ('jc', models.CharField(max_length=40, null=True, verbose_name='简称')),
                ('code', models.CharField(max_length=20, null=True, verbose_name='品号')),
                ('name', models.CharField(max_length=520, null=True, verbose_name='品名     .')),
                ('spec', models.CharField(max_length=520, null=True, verbose_name='规格     .')),
                ('unit', models.CharField(max_length=6, null=True, verbose_name='计量单位')),
                ('quan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='采购量')),
                ('okquan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='已交数量')),
                ('noquan', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='未交量')),
                ('currenct', models.CharField(max_length=10, null=True, verbose_name='币别')),
                ('price', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='采购单价')),
                ('rate', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='税率')),
                ('notex', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='未交未税金额')),
                ('tex', models.DecimalField(decimal_places=0, max_digits=14, null=True, verbose_name='税额')),
                ('allchash', models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='未交含税金额')),
                ('sclass', models.CharField(max_length=20, null=True, verbose_name='分类')),
                ('predate', models.DateField(null=True, verbose_name='要求到货日')),
                ('sbill', models.CharField(max_length=40, null=True, verbose_name='来源单号')),
                ('PO', models.CharField(max_length=20, null=True, verbose_name='PO')),
                ('buyer', models.CharField(max_length=20, null=True, verbose_name='采购人员')),
                ('checker', models.CharField(max_length=20, null=True, verbose_name='审核者')),
                ('tao', models.CharField(max_length=40, null=True, verbose_name='tao料号')),
                ('company', models.CharField(max_length=40, null=True, verbose_name='公司')),
                ('sno', models.CharField(max_length=40, null=True, verbose_name='供方编号')),
                ('billno', models.CharField(max_length=60, unique=True, verbose_name='采购单号序号')),
                ('note', models.TextField(null=True, verbose_name='备注')),
                ('sdate', models.DateField(null=True, verbose_name='供方回复到货日')),
                ('snote', models.CharField(blank=True, max_length=20, null=True, verbose_name='供方说明')),
                ('retime', models.DateTimeField(null=True, verbose_name='回复时间')),
                ('reman', models.CharField(max_length=20, null=True, verbose_name='回复人 ')),
                ('zc', models.CharField(max_length=7, null=True, verbose_name='周次 ')),
                ('buyercode', models.CharField(max_length=20, null=True, verbose_name='采购员编码')),
                ('ok', models.BooleanField(choices=[(True, '完成'), (False, '未完成')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '采购交期供应商确认',
                'verbose_name_plural': '采购交期供应商确认',
                'db_table': 'filterpmdn200',
                'ordering': ['-predate', 'billno'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='bill',
            field=models.ForeignKey(limit_choices_to={'ok': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.filterpmdn200', verbose_name='采购单'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='发货单号码'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='unitcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收货单位名称'),
        ),
    ]
