# Generated by Django 2.0.8 on 2019-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appalarmset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snid', models.CharField(max_length=40, verbose_name='结果')),
                ('sn', models.CharField(max_length=20, verbose_name='设备号')),
                ('action', models.CharField(max_length=20, verbose_name='动作')),
                ('mobtype', models.CharField(max_length=40, verbose_name='机型')),
                ('Country', models.CharField(max_length=40, verbose_name='国家')),
                ('creatdate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uuid', models.CharField(max_length=150, verbose_name='uuid')),
                ('devname', models.CharField(max_length=150, verbose_name='设备名称')),
                ('mobname', models.CharField(max_length=40, verbose_name='手机名称')),
                ('mobver', models.CharField(max_length=40, verbose_name='手机版本')),
                ('mobid', models.CharField(max_length=40, verbose_name='手机标识')),
                ('mobidver', models.CharField(max_length=40, verbose_name='手机标识版本')),
                ('firmver', models.CharField(max_length=40, verbose_name='固件版本')),
                ('longitude', models.CharField(max_length=40, verbose_name='经度')),
                ('latitude', models.CharField(max_length=40, verbose_name='维度')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('mobidname', models.CharField(max_length=40, verbose_name='手机标识名')),
                ('speed', models.FloatField(default=0, verbose_name='速度')),
                ('altitude', models.CharField(max_length=40, verbose_name='海拔高度')),
            ],
            options={
                'verbose_name': '智能灯日志',
                'verbose_name_plural': '智能灯日志',
                'db_table': 'appalarmset',
                'ordering': ['-creatdate'],
                'managed': False,
            },
        ),
    ]
