# Generated by Django 2.1 on 2019-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalarmset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='getsmm',
            fields=[
                ('interid', models.IntegerField(primary_key=True, serialize=False, verbose_name='interid')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.CharField(max_length=20, verbose_name='价格')),
                ('aver', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='价格')),
                ('today', models.CharField(max_length=20, verbose_name='日期')),
                ('creatdate', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '上海有色金属交易价格',
                'verbose_name_plural': '上海有色金属交易价格',
                'db_table': 'getsmm',
                'ordering': ['-creatdate', 'name'],
                'managed': False,
            },
        ),
    ]
